name: Sync Translations

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy translations to Translations repository
        run: |
          mkdir Translations
          git clone git@github.com:MUtils-MC/Translations.git
          cd Translations
          git config --global user.name "Miraculixx-Bot"
          git config --global user.email "miraculixxt@users.noreply.github.com"
          cp ${{ github.workspace }}/data/language/en.yml ./mtimer/en.yml
          git add .
          git commit -m "Update new MTimer translation keys"
          git push
