name: Sync Translations

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy translations to Translations repository
        run: |
          mkdir Translations
          cd Translations
          git clone https://github.com/MUtils-MC/Translations.git
          ls
          cp ${{ github.workspace }}/data/language/en.yml ./MTimer/en.yml
          git add .
          git commit -m "Update new MTimer translation keys"
          git push
